// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: commits.proto

package commits

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepoCommiFetchDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepositoryName string `protobuf:"bytes,1,opt,name=repositoryName,proto3" json:"repositoryName,omitempty"`
}

func (x *RepoCommiFetchDataRequest) Reset() {
	*x = RepoCommiFetchDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commits_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepoCommiFetchDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoCommiFetchDataRequest) ProtoMessage() {}

func (x *RepoCommiFetchDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commits_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoCommiFetchDataRequest.ProtoReflect.Descriptor instead.
func (*RepoCommiFetchDataRequest) Descriptor() ([]byte, []int) {
	return file_commits_proto_rawDescGZIP(), []int{0}
}

func (x *RepoCommiFetchDataRequest) GetRepositoryName() string {
	if x != nil {
		return x.RepositoryName
	}
	return ""
}

type RepoCommitFetchDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastFetchTime string `protobuf:"bytes,1,opt,name=lastFetchTime,proto3" json:"lastFetchTime,omitempty"`
}

func (x *RepoCommitFetchDataResponse) Reset() {
	*x = RepoCommitFetchDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commits_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepoCommitFetchDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoCommitFetchDataResponse) ProtoMessage() {}

func (x *RepoCommitFetchDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commits_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoCommitFetchDataResponse.ProtoReflect.Descriptor instead.
func (*RepoCommitFetchDataResponse) Descriptor() ([]byte, []int) {
	return file_commits_proto_rawDescGZIP(), []int{1}
}

func (x *RepoCommitFetchDataResponse) GetLastFetchTime() string {
	if x != nil {
		return x.LastFetchTime
	}
	return ""
}

var File_commits_proto protoreflect.FileDescriptor

var file_commits_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x22, 0x43, 0x0a, 0x19, 0x52, 0x65, 0x70, 0x6f,
	0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x43, 0x0a,
	0x1b, 0x52, 0x65, 0x70, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0d,
	0x6c, 0x61, 0x73, 0x74, 0x46, 0x65, 0x74, 0x63, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x46, 0x65, 0x74, 0x63, 0x68, 0x54, 0x69,
	0x6d, 0x65, 0x32, 0x74, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x62, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x12, 0x22,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x70,
	0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_commits_proto_rawDescOnce sync.Once
	file_commits_proto_rawDescData = file_commits_proto_rawDesc
)

func file_commits_proto_rawDescGZIP() []byte {
	file_commits_proto_rawDescOnce.Do(func() {
		file_commits_proto_rawDescData = protoimpl.X.CompressGZIP(file_commits_proto_rawDescData)
	})
	return file_commits_proto_rawDescData
}

var file_commits_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_commits_proto_goTypes = []interface{}{
	(*RepoCommiFetchDataRequest)(nil),   // 0: commits.RepoCommiFetchDataRequest
	(*RepoCommitFetchDataResponse)(nil), // 1: commits.RepoCommitFetchDataResponse
}
var file_commits_proto_depIdxs = []int32{
	0, // 0: commits.CommitsService.GetRepoCommitFetchData:input_type -> commits.RepoCommiFetchDataRequest
	1, // 1: commits.CommitsService.GetRepoCommitFetchData:output_type -> commits.RepoCommitFetchDataResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_commits_proto_init() }
func file_commits_proto_init() {
	if File_commits_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_commits_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepoCommiFetchDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commits_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepoCommitFetchDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_commits_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_commits_proto_goTypes,
		DependencyIndexes: file_commits_proto_depIdxs,
		MessageInfos:      file_commits_proto_msgTypes,
	}.Build()
	File_commits_proto = out.File
	file_commits_proto_rawDesc = nil
	file_commits_proto_goTypes = nil
	file_commits_proto_depIdxs = nil
}
