// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: repos.proto

package repos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RepositoriesServiceClient is the client API for RepositoriesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RepositoriesServiceClient interface {
	GetRepositories(ctx context.Context, in *GetRepositoriesRequest, opts ...grpc.CallOption) (*GetRepositoriesResponse, error)
	GetReposFetchHistory(ctx context.Context, in *GetReposFetchHistoryRequest, opts ...grpc.CallOption) (*GetReposFetchHistoryResponse, error)
	GetRepositoryNames(ctx context.Context, in *GetRepositoryNamesRequest, opts ...grpc.CallOption) (*GetRepositoryNamesResponse, error)
}

type repositoriesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRepositoriesServiceClient(cc grpc.ClientConnInterface) RepositoriesServiceClient {
	return &repositoriesServiceClient{cc}
}

func (c *repositoriesServiceClient) GetRepositories(ctx context.Context, in *GetRepositoriesRequest, opts ...grpc.CallOption) (*GetRepositoriesResponse, error) {
	out := new(GetRepositoriesResponse)
	err := c.cc.Invoke(ctx, "/repos.RepositoriesService/GetRepositories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoriesServiceClient) GetReposFetchHistory(ctx context.Context, in *GetReposFetchHistoryRequest, opts ...grpc.CallOption) (*GetReposFetchHistoryResponse, error) {
	out := new(GetReposFetchHistoryResponse)
	err := c.cc.Invoke(ctx, "/repos.RepositoriesService/GetReposFetchHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoriesServiceClient) GetRepositoryNames(ctx context.Context, in *GetRepositoryNamesRequest, opts ...grpc.CallOption) (*GetRepositoryNamesResponse, error) {
	out := new(GetRepositoryNamesResponse)
	err := c.cc.Invoke(ctx, "/repos.RepositoriesService/GetRepositoryNames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepositoriesServiceServer is the server API for RepositoriesService service.
// All implementations must embed UnimplementedRepositoriesServiceServer
// for forward compatibility
type RepositoriesServiceServer interface {
	GetRepositories(context.Context, *GetRepositoriesRequest) (*GetRepositoriesResponse, error)
	GetReposFetchHistory(context.Context, *GetReposFetchHistoryRequest) (*GetReposFetchHistoryResponse, error)
	GetRepositoryNames(context.Context, *GetRepositoryNamesRequest) (*GetRepositoryNamesResponse, error)
	mustEmbedUnimplementedRepositoriesServiceServer()
}

// UnimplementedRepositoriesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRepositoriesServiceServer struct {
}

func (UnimplementedRepositoriesServiceServer) GetRepositories(context.Context, *GetRepositoriesRequest) (*GetRepositoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepositories not implemented")
}
func (UnimplementedRepositoriesServiceServer) GetReposFetchHistory(context.Context, *GetReposFetchHistoryRequest) (*GetReposFetchHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReposFetchHistory not implemented")
}
func (UnimplementedRepositoriesServiceServer) GetRepositoryNames(context.Context, *GetRepositoryNamesRequest) (*GetRepositoryNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepositoryNames not implemented")
}
func (UnimplementedRepositoriesServiceServer) mustEmbedUnimplementedRepositoriesServiceServer() {}

// UnsafeRepositoriesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RepositoriesServiceServer will
// result in compilation errors.
type UnsafeRepositoriesServiceServer interface {
	mustEmbedUnimplementedRepositoriesServiceServer()
}

func RegisterRepositoriesServiceServer(s grpc.ServiceRegistrar, srv RepositoriesServiceServer) {
	s.RegisterService(&RepositoriesService_ServiceDesc, srv)
}

func _RepositoriesService_GetRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepositoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoriesServiceServer).GetRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repos.RepositoriesService/GetRepositories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoriesServiceServer).GetRepositories(ctx, req.(*GetRepositoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoriesService_GetReposFetchHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReposFetchHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoriesServiceServer).GetReposFetchHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repos.RepositoriesService/GetReposFetchHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoriesServiceServer).GetReposFetchHistory(ctx, req.(*GetReposFetchHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoriesService_GetRepositoryNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepositoryNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoriesServiceServer).GetRepositoryNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repos.RepositoriesService/GetRepositoryNames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoriesServiceServer).GetRepositoryNames(ctx, req.(*GetRepositoryNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RepositoriesService_ServiceDesc is the grpc.ServiceDesc for RepositoriesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RepositoriesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "repos.RepositoriesService",
	HandlerType: (*RepositoriesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRepositories",
			Handler:    _RepositoriesService_GetRepositories_Handler,
		},
		{
			MethodName: "GetReposFetchHistory",
			Handler:    _RepositoriesService_GetReposFetchHistory_Handler,
		},
		{
			MethodName: "GetRepositoryNames",
			Handler:    _RepositoriesService_GetRepositoryNames_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "repos.proto",
}
